# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

services:
  otel-collector:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${HOST_FILESYSTEM}:/hostfs:ro
      - ${DOCKER_SOCK}:/var/run/docker.sock:ro
      - ${OTEL_COLLECTOR_CONFIG}:/etc/otelcol-config.yml
      - ./kopai/otelcol-config-kopai.yml:/etc/otelcol-config-extras.yml
