# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

exporters:
  otlp_http/kopai:
    endpoint: https://demo-otlp.kopai.app

service:
  pipelines:
    traces:
      exporters: [spanmetrics, otlp_http/kopai, debug]
    metrics:
      exporters: [otlp_http/kopai, debug]
    logs:
      exporters: [otlp_http/kopai, debug]
