# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

# Export to localhost:4318
exporters:
  otlphttp/localhost:
    endpoint: http://host.docker.internal:4318
    encoding: json
    compression: none

service:
  pipelines:
    traces:
      exporters: [spanmetrics, otlphttp/localhost, debug]
    metrics:
      exporters: [otlphttp/localhost, debug]
    logs:
      exporters: [otlphttp/localhost, debug]
